spring:
  profiles.active: "FS"
  main.banner-mode: "off"
  servlet.multipart:
    max-file-size: 11MB
    max-request-size: 110MB
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: file:src/main/resources/fs/
    livereload:
      enabled: true
      thymeleaf:
        cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/ESG_HOMEPAGE?autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: dpvmdptm1!
  sql.init.platform: mariadb
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
      static-locations[0]: file:src/main/resources/fs/
      static-locations[1]: classpath:/fs/
#      add-mappings: false
server:
  port: 8088
  servlet:
    session:
      timeout: 108000 # 60s * 60m * 30h
      tracking-modes: cookie # url에 jsession 처리
  address: 0.0.0.0
logging:
  pattern.file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback.rollingpolicy.file-name-pattern: "./logs/archives/app.log.%d{yyyy-MM-dd}.%i.log.gz"
  file:
    name: ./logs/app.log
    max-history: 60
    max-size: 50MB
  level:
    kr.fscom.esg: INFO
    org:
      springfremework.web: INFO
      quartz.core: INFO
      hibernate: OFF
      hibernate.SQL: OFF
      hibernate.type.descriptor.sql.BasicBinder: TRACE
mybatis.mapper-locations: classpath:mapper/**/*.xml
springdoc:
  swagger-ui:
    path: /doc
esg:
  upload-path: /Users/user/Documents/dev/esg
