spring:
  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
      additional-paths: classpath:/fs/
    livereload:
      enabled: true
      thymeleaf:
        cache: false

  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
